### ISSUE TITLE
Integrate the ML model into our codebase

### ISSUE THREAD

**Issue by EddieShao** [KirillTregubov/csc302#35]
- Put the ML model code into our codebase.
- Create a black-box interface function that generates song recommendations based on song inputs (for the backend to use).
- Truncate the pre-computed dataset until it's small enough to be pushed to Github.

**Comment by pvtstaticvoid** [comment]
@EddieShao see PR #39.

**Comment by KirillTregubov** [comment]
Bump as a task for this week.
